package com.corespark.pccompiler.utility


/**
 * @author Zachy Bazov.
 * @since 21/12/2018.
 * CoreSpark Ltd.
 * PCCompiler.
 * All Rights Reserved. Copyright (c) 2018.
 */
const val KEY_IS_AUTHENTICATED  = "isAuthenticated"
const val KEY_USRENAME          = "username"
const val KEY_PASSWORD          = "password"

const val TABLE_CPU             = "CPU"
const val TABLE_OPT_DRIVE       = "OpticalDrive"
const val TABLE_COOLER          = "Cooler"
const val TABLE_GRAPHIC_CARD    = "GraphicCard"
const val TABLE_MOTHERBOARD     = "Motherboard"
const val TABLE_SOUND_CARD      = "SoundCard"
const val TABLE_MEMORY          = "Memory"
const val TABLE_POWER_SUPPLY    = "PowerSupply"
const val TABLE_STORAGE         = "Storage"
const val TABLE_CASE            = "Case"
const val TABLE_EXT_STORAGE     = "ExternalStorage"
const val TABLE_OP_SYSTEM       = "OS"
const val TABLE_COMPILATION     = "Compilation"

const val KEY_MANUFACTURER      = "manufacturer"
const val KEY_CPU               = "cpu"
const val KEY_CORE              = "core"
const val KEY_SPEED             = "speed"
const val KEY_TDP               = "tdp"
const val KEY_PRICE             = "price"
const val KEY_COOLER            = "cooler"
const val KEY_RPM               = "rpm"
const val KEY_NOISE             = "noise"
const val KEY_MOTHERBOARD       = "motherboard"
const val KEY_SOCKET_CPU        = "socketcpu"
const val KEY_FORM_FACTOR       = "formfactor"
const val KEY_RAM_SLOTS         = "ramslots"
const val KEY_MAX_RAM           = "maxram"
const val KEY_RAM               = "ram"
const val KEY_TYPE              = "type"
const val KEY_MODULES           = "modules"
const val KEY_CAS               = "cas"
const val KEY_SIZE              = "size"
const val KEY_GB_PRICE          = "gbprice"
const val KEY_STORAGE           = "storage"
const val KEY_SERIES            = "series"
const val KEY_FORM              = "form"
const val KEY_CACHE             = "cache"
const val KEY_CAPACITY          = "capacity"
const val KEY_OPTICAL_DRIVE     = "opticaldrive"
const val KEY_BD                = "bd"
const val KEY_CD                = "cd"
const val KEY_DVD               = "dvd"
const val KEY_BD_WRITE          = "bdwrite"
const val KEY_CD_WRITE          = "cdwrite"
const val KEY_DVD_WRITE         = "dvdwrite"
const val KEY_GRAPHIC_CARD      = "graphiccard"
const val KEY_CHIPSET           = "chipset"
const val KEY_MEMORY            = "memory"
const val KEY_CORE_CLOCK        = "coreclock"
const val KEY_SOUND_CARD        = "soundcard"
const val KEY_BITS              = "bits"
const val KEY_SNR               = "snr"
const val KEY_CHANNELS          = "channels"
const val KEY_RATE              = "rate"
const val KEY_POWER_SUPPLY      = "powersupply"
const val KEY_EFFICIENCY        = "efficiency"
const val KEY_MODULAR           = "modular"
const val KEY_WATTS             = "watts"
const val KEY_CASE              = "case"
const val KEY_EXTERNAL          = "external"
const val KEY_INTERNAL          = "internal"
const val KEY_OPERATING_SYSTEM  = "operatingsystem"
const val KEY_USER              = "user"